### PR TITLE
Merge branch into master for essential changes to CI and backend config, and maintain branch for ongoing development.

### LINKED ISSUE #9: Set up express.js on Node.js
https://www.npmjs.com/package/express

### PR DESCRIPTION
**Pull request by deeyonn**
I would like to merge the following essential changes to master to test if the CI workflow I built is working.

Resolves #9

### CODE REVIEW

**Comment by deeyonn** [comment]
yo, i don't know what's wrong with my `.github/workflows/node.js.yaml` configuration. It keeps getting stuck at `Waiting for a runner to pick up this job...`

**Comment by deeyonn** [comment]
> yo, i don't know what's wrong with my `.github/workflows/node.js.yaml` configuration. It keeps getting stuck at `Waiting for a runner to pick up this job...`

Fixed it

**Review by yiyefyy — APPROVED** [review]
lgtm!

**Review by xiaoying1129 — APPROVED** [review]
lgtm!

**Comment by wxy1203** [comment]
LGTM

**Review by wxy1203 — APPROVED** [review]
LGTM

**Review by lleyi0606 — APPROVED** [review]
lgtm

**Pull request merged**
